# Generated by Django 5.2.1 on 2025-05-21 05:11

import CarDekho_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDekho_app', '0002_carlist_chassinumber_carlist_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroomlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='carlist',
            name='chassinumber',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[CarDekho_app.models.alphanumeric]),
        ),
    ]
